### PR TITLE
DM-34340: Adapt to daf_butler API changes.

### PR DESCRIPTION
**Pull request by TallJimbo**

### CODE REVIEW

**Comment by timj** [comment]
@TallJimbo The Jira ticket is closed that is associated with this PR so is this PR still needed (I think so) or should it be closed?

**Comment by TallJimbo** [comment]
Oof, yes, this ticket definitely needs to get merged now.  I vaguely remember passing the responsibility of merging it off to @mfisherlevine for some reason that I now forget, but we probably miscommunicated.  I'll rebase and merge along with DM-41326 (merge is now in progress, and will have already broken this).  Good catch!

**Comment by TallJimbo** [comment]
Ok, good news is that the adaptations to the deprecations seem to have already been made on other tickets.  After rebase I think there's still stuff worth keeping on this ticket, so my plan is to finish the rest of the DM-41326 merge, then run a another ci_summit Jenkins with this before merging it.

**Comment by TallJimbo** [comment]
Accidentally closed due to git mistakes.  Reopening.

**Comment by timj** [comment]
I was also trying to fix the matplotlib mypy on #116 so thanks for this. I was considering pinning matplotlib version.

**Review by mfisherlevine — APPROVED** [review]
LGTM, sorry for the extreme delay here!

**Pull request merged**
